name: byte_treasurer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.8
  desktop_drop: ^0.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  yaml: ^3.1.3
  yaml_writer: ^2.1.0
  jinja: ^0.6.5
  panes: ^1.1.0
  just_the_tooltip: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/builtin_tools.yaml
